version: "3.9"

services:

  db:
    image: postgres:15
    container_name: relief-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reliefdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: relief-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/reliefdb
      JWT_SECRET: changeme
      BASE_URL: http://localhost:5173
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: relief-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: http://localhost:3000
      VITE_BACKEND_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data: